var res = {
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    boton_jugar_png : "res/boton_jugar.png",
    menu_titulo1_png : "res/titulo_normal.png",
    menu_titulo2_png : "res/Titulo_Ice.png",
    menu_titulo3_png : "res/Titulo_Aire.png",
    menu_titulo4_png: "res/Titulo_Fire.png",
    tiles2_png: "res/Tiles2.png",
    map1_tmx: "res/Map1.tmx",
    map2_tmx: "res/Map2.tmx",
    tomate_png : "res/tomate.png",
    tomate_plist : "res/tomate.plist",
    playerrunright_png : "res/walkingRight.png",
    playerrunright_plist : "res/walkingRight.plist",
    hielowalkright_png : "res/WalkingHielo.png",
    hielowalkright_plist : "res/WalkingHielo.plist",
    fuegowalkright_png: "res/WalkingFuego.png",
    fuegowalkright_plist: "res/WalkingFuego.plist",
    airewalkright_png: "res/walkingAire.png",
    airewalkright_plist: "res/walkingAire.plist",
    playerimpactado_png: "res/impactado.png",
    playerimpactado_plist: "res/impactado.plist",
    playerjumpright_png : "res/jumpingRight.png",
    playerjumpright_plist : "res/jumpingRight.plist",
    hielojumpright_png : "res/jumpingHielo.png",
    hielojumpright_plist : "res/jumpingHielo.plist",
    fuegojumpright_png: "res/jumpingFuego.png",
    fuegojumpright_plist: "res/jumpingFuego.plist",
    airejumpright_png: "res/jumpingAire.png",
    airejumpright_plist: "res/jumpingAire.plist",
    playeridleright_png : "res/idleRight.png",
    playeridleright_plist : "res/idleRight.plist",
    hieloidleright_png : "res/idleHielo.png",
    hieloidleright_plist : "res/idleHielo.plist",
    fuegoidleright_png: "res/idleFuego.png",
    fuegoidleright_plist: "res/idleFuego.plist",
    aireidleright_png: "res/idleAire.png",
    aireidleright_plist: "res/idleAire.plist",
    playerfloatright_png : "res/floatRight.png",
    playerfloatright_plist : "res/floatRight.plist",
    hielofloatright_png : "res/floatHielo.png",
    hielofloatright_plist : "res/floatHielo.plist",
    fuegofloatright_png: "res/floatFuego.png",
    fuegofloatright_plist: "res/floatFuego.plist",
    airefloatright_png: "res/floatAire.png",
    airefloatright_plist: "res/floatAire.plist",
    disparohielo_png : "res/ShootHielo.png",
    disparohielo_plist : "res/ShootHielo.plist",
    disparofuego_png : "res/ShootFire.png",
    disparofuego_plist : "res/ShootFire.plist",
    disparoaire_png : "res/ShootWind.png",
    disparoaire_plist : "res/ShootWind.plist",
    animacion_enemigo_png: "res/Enemy.png",
    animacion_enemigo_plist: "res/Enemy.plist",
    forestmusic_mp3: "res/forestMusic.mp3",
    moonlightmusic_mp3: "res/moonlightMusic.mp3",
    figuraPingu_png: "res/figura_pinguino.png",
    figuraPingu_plist: "res/figura_pinguino.plist",
    figuraFuego_png: "res/figura_fuego.png",
    figuraFuego_plist: "res/figura_fuego.plist",
    figuraAire_png: "res/figura_aire.png",
    figuraAire_plist: "res/figura_aire.plist",
    bloqueHielo_png: "res/bloqueHielo.png",
    bloqueHielo_plist: "res/bloqueHielo.plist",
    obstaculoHielo_png: "res/obstaculoHielo.png",
    obstaculoHielo_plist: "res/obstaculoHielo.plist",
    tronco_png: "res/Tree.png",
    tronco_plist: "res/Tree.plist",
    dispararHielo_png: "res/dispararHielo.png",
    dispararHielo_plist: "res/dispararHielo.plist",
    dispararFuego_png: "res/dispararFuego.png",
    dispararFuego_plist: "res/dispararFuego.plist",
    dispararAire_png: "res/DispararAire.png",
    dispararAire_plist: "res/DispararAire.plist",
    transformationsound_wav: "res/tansformation_sound.wav",
    lostsound_wav: "res/lost_sound.wav",
    jumpsound_wav: "res/jump_sound.wav",
    fireshootsound_wav: "res/fireshoot_sound.wav",
    floatsound_wav: "res/float_sound.wav",
    hittedsound_wav: "res/hitted_sound.wav",
    passedsound_wav: "res/victory_funny_sound.wav",
    kirbysayshi_wav: "res/kirby_says_hi.wav",
    kirbyintromusic_mp3: "res/kirby_intro.mp3",
    point_wav: "res/point.wav",
    life_png: "res/lifeYay.png",
    goal_png: "res/DoorSea.png",
    goal_plist: "res/DoorSea.plist"

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}